version: '3'
services:
  local-db:
    image: library/mysql:5.7
    container_name: infra-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: local_admin
      TZ: Asia/Seoul
    volumes:
      - ../db/mysql/data:/var/lib/mysql
      - ../db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/amd64